version: '3.8'

services:
  db:
    image: postgres:15
    container_name: livraria_postgres
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: catalogodosabio
      POSTGRES_PASSWORD: desafio_santander
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always